{{- if .Values.postgres.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: pg-restore
spec:
  schedule: "0 0 * * *"
  suspend: true
  jobTemplate:
    spec:
      template:
        spec:
          enableServiceLinks: false
          containers:
          - name: dbtools
            image: "{{ .Values.image.containerRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["/bin/bash", "pg_restore.sh"]
            env:
              - name: PG_HOST
                value: "pg"
              - name: PG_USER
                value: "shared"
              - name: PG_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: pg-secrets
                    key: password
              - name: PG_DATABASE
                value: "shared"
              - name: PG_BACKUP_LOCATION
                value: "{{ .Values.pgBackup.location }}"
            volumeMounts:
              - mountPath: "/usr/src/credentials"
                name: application-credentials
                readOnly: true
          restartPolicy: Never
          volumes:
            - name: application-credentials
              secret:
                secretName: gcp-sa-secret
                items:
                  - key: secret-access-credentials
                    path: application-credentials.json
{{- end }}
