{{- if .Values.mysql.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: skywin-delete-requests
spec:
  schedule: "0 7 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          enableServiceLinks: false
          containers:
          - name: dbtools
            image: "{{ .Values.image.containerRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["/bin/bash", "skywin_reset_wishlist.sh", "delete"]
            env:
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-secrets
                    key: user
          restartPolicy: Never
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: skywin-shuffle-requests
spec:
  schedule: "0 8 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          enableServiceLinks: false
          containers:
          - name: dbtools
            image: "{{ .Values.image.containerRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            command: ["/bin/bash", "skywin_reset_wishlist.sh", "shuffle"]
            env:
              - name: MYSQL_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: mysql-secrets
                    key: user
          restartPolicy: Never
{{- end }}
