version: 2
registries:
  google-artifact-registry:
    type: docker-registry
    url: europe-west1-docker.pkg.dev
    username: _json_key
    password: ${{ secrets.GCP_SA_KEY }}
updates:
  # Docker
  - package-ecosystem: "docker"
    directory: "/apps/db-tools"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/apps/skywinone"
    schedule:
      interval: "weekly"
  - package-ecosystem: "docker"
    directory: "/apps/weather"
    schedule:
      interval: "weekly"

  # Helm
  - package-ecosystem: "helm"
    directory: "/charts/acme-sync"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/argo-cd"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/insidan-api"
    schedule:
      interval: "daily"
    registries:
      - google-artifact-registry
  - package-ecosystem: "helm"
    directory: "/charts/insidan-web"
    schedule:
      interval: "daily"
    registries:
      - google-artifact-registry
  - package-ecosystem: "helm"
    directory: "/charts/kanidm"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/mysql"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/postgres"
    schedule:
      interval: "weekly"
  - package-ecosystem: "helm"
    directory: "/charts/secret-store"
    schedule:
      interval: "weekly"

  # Python (weather app)
  - package-ecosystem: "pip"
    directory: "/apps/weather"
    schedule:
      interval: "weekly"
