oauth2:
  clientId: insidan
  clientSecretRef: authelia-client-insidan-secret
  authUrl: https://auth.linkopingsfallskarmsklubb.se/api/oidc/authorization
  tokenUrl: https://auth.linkopingsfallskarmsklubb.se/api/oidc/token
  redirectUrl: http://localhost/api/auth/callback
  defaultRedirect: http://localhost

skywin:
  url: http://skywinone:8080/skywinone

skywinDb:
  uriRef: insidandev-mysql-uri
