oauth2:
  clientId: insidan
  clientSecretRef: authelia-client-insidan-secret
  authUrl: http://auth.local.localhost/api/oidc/authorization
  tokenUrl: http://auth.local.localhost/api/oidc/token
  redirectUrl: http://localhost:3000/api/auth/callback
  defaultRedirect: http://localhost:3000/

skywin:
  url: http://skywinone:8080/skywinone

skywinDb:
  uriRef: insidandev-mysql-uri
