apiVersion: batch/v1
kind: CronJob
metadata:
  name: weather
spec:
  schedule: "* * * * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: weather
            image: "{{ .Values.image.containerRegistry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
            env:
              - name: HOLFUY_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: holfuy-api-key
                    key: key
              - name: POSTGRES_URL
                valueFrom:
                  secretKeyRef:
                    name: postgres-url
                    key: url
              - name: LFV_URL
                value: "{{ .Values.lfvUrl }}"
          restartPolicy: Never

