---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: holfuy-api-key
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: ClusterSecretStore
  target:
    name: holfuy-api-key
    creationPolicy: Owner
  data:
    - secretKey: key
      remoteRef:
        key: {{ .Values.holfuyApiKeyRef }}

---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-url
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: ClusterSecretStore
  target:
    name: postgres-url
    creationPolicy: Owner
  data:
    - secretKey: url
      remoteRef:
        key: {{ .Values.pgUrlRef }}
