image:
  containerRegistry: europe-west1-docker.pkg.dev
  repository: bitnami-ch3rudc/docker/dbtools
  tag: "1.0.3"
  pullPolicy: IfNotPresent

postgres:
  enabled: true

mysql:
  enabled: true

skywinBackup:
  location: gs://lfk-backup-prod/skywin

pgBackup:
  location: gs://lfk-backup-prod/postgres
