replicaCount: 1
image:
  containerRegistry: europe-west1-docker.pkg.dev
  repository: bitnami-ch3rudc/docker/insidanapi
  tag: "0.0.22"
  pullPolicy: Always

secretStore: secret-store

oauth2:
  clientId: insidan
  clientSecretRef: insidan-client-secret
  authUrl: https://idm.linkopingsfallskarmsklubb.se/ui/oauth2
  tokenUrl: https://idm.linkopingsfallskarmsklubb.se/oauth2/token
  redirectUrl: https://insidan.linkopingsfallskarmsklubb.se/api/auth/callback
  defaultRedirect: /

kanidm:
  url: https://idm.linkopingsfallskarmsklubb.se
  tokenRef: insidan-kanidm-token

skywin:
  url: http://192.168.30.114/skywinone
  user: insidanapi
  passwordRef: insidan-skywin-password
  register: 113

skywinDb:
  uriRef: insidan-mysql-uri

commonDb:
  uriRef: postgres-url

smtp:
  server: smtp-relay.gmail.com
  sender: Linköpings Fallskärmsklubb <do-not-reply@linkopingsfallskarmsklubb.se>