replicaCount: 1
image:
  containerRegistry: europe-west1-docker.pkg.dev
  repository: bitnami-ch3rudc/docker/insidanapi
  tag: "0.0.25"
  pullPolicy: Always

secretStore: secret-store

server:
  host: "0.0.0.0"
  port: 8000
  cookieDomain: "linkopingsfallskarmsklubb.se"

oauth2:
  clientId: insidan
  clientSecretRef: authelia-client-insidan-secret
  authUrl: https://auth.linkopingsfallskarmsklubb.se/api/oidc/authorization
  tokenUrl: https://auth.linkopingsfallskarmsklubb.se/api/oidc/token
  redirectUrl: https://insidan.linkopingsfallskarmsklubb.se/api/auth/callback
  defaultRedirect: https://insidan.linkopingsfallskarmsklubb.se/
  scopes: "[openid,profile,email,groups,offline_access]"

authelia:
  url: https://auth.linkopingsfallskarmsklubb.se

lldap:
  url: http://lldap.authelia.svc.cluster.local:17170
  ldapUrl: ldap://lldap.authelia.svc.cluster.local:3890
  username: admin
  passwordRef: lldap-user-pass

skywin:
  url: http://192.168.30.114/skywinone
  user: insidanapi
  passwordRef: insidan-skywin-password
  register: 113

skywinDb:
  uriRef: insidan-mysql-uri

commonDb:
  uriRef: postgres-url

smtp:
  server: smtp-relay.gmail.com
  sender: Linköpings Fallskärmsklubb <do-not-reply@linkopingsfallskarmsklubb.se>
