apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: {{ .Release.Name }}-oidc
spec:
  plugin:
    traefik-oidc-auth:
      Secret: "urn:k8s:secret:{{ .Release.Name }}-secret:pluginSecret"
      CallbackUri: /skywinone/oidc/callback
      Provider:
        Url: {{ .Values.providerUrl }}
        Issuer: {{ .Values.providerUrl }}
        ClientId: {{ .Values.clientId }}
        ClientSecret: "urn:k8s:secret:{{ .Release.Name }}-secret:providerClientSecret"
        UsePkce: true
      Scopes: ["openid", "profile", "email", "groups"]
