host: insidan.linkopingsfallskarmsklubb.se
localHost: 192.168.30.114
secretStore: secret-store
providerUrl: https://auth.linkopingsfallskarmsklubb.se
clientId: insidan
pluginSecretRef: skywinone-plugin-secret
providerClientSecretRef: authelia-client-insidan-secret
