replicaCount: 1

image:
  containerRegistry: europe-west1-docker.pkg.dev
  repository: bitnami-ch3rudc/docker/skywinone
  tag: "25.0.3"
  pullPolicy: IfNotPresent

secretStore: secret-store
skywinonePropertiesRef: skywinone-properties