{{- if not .Values.proxy }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}
    spec:
      containers:
        - name: api
          image: "europe-west1-docker.pkg.dev/bitnami-ch3rudc/docker/insidanapi:{{ .Chart.AppVersion }}"
          imagePullPolicy: Always
          env:
            - name: API_SERVER__HOST
              value: "0.0.0.0"
            - name: API_SERVER__PORT
              value: "8000"
            - name: API_OAUTH2__CLIENT_ID
              value: {{ .Values.oauth2.clientId }}
            - name: API_OAUTH2__CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: insidan-client-secret
            - name: API_OAUTH2__AUTH_URL
              value: {{ .Values.oauth2.authUrl }}
            - name: API_OAUTH2__TOKEN_URL
              value: {{ .Values.oauth2.tokenUrl }}
            - name: API_OAUTH2__REDIRECT_URL
              value: {{ .Values.oauth2.redirectUrl }}
            - name: API_OAUTH2__DEFAULT_REDIRECT
              value: {{ .Values.oauth2.defaultRedirect }}
            - name: API_OAUTH2__SCOPES
              value: "[openid,profile,email,groups]"
            - name: API_KANIDM__URL
              value: {{ .Values.kanidm.url }}
            - name: API_KANIDM__TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: kanidm-token
            - name: API_SKYWIN__URL
              value: {{ .Values.skywin.url }}
            - name: API_SKYWIN__USER
              value: {{ .Values.skywin.user }}
            - name: API_SKYWIN__PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: skywin-password
            - name: API_SKYWIN__REGISTER
              value: "{{ .Values.skywin.register }}"
            - name: API_SKYWIN_DB__URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: skywin-db-uri
            - name: API_COMMON_DB__URI
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}
                  key: common-db-uri
            - name: API_SMTP__SERVER
              value: {{ .Values.smtp.server }}
            - name: API_SMTP__SENDER
              value: {{ .Values.smtp.sender }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
{{- end }}
