apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Release.Name }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.secretStore }}
    kind: ClusterSecretStore
  target:
    name: {{ .Release.Name }}
    creationPolicy: Owner
  data:
    - secretKey: insidan-client-secret
      remoteRef:
        key: {{ .Values.oauth2.clientSecretRef }}
    - secretKey: kanidm-token
      remoteRef:
        key: {{ .Values.kanidm.tokenRef }}
    - secretKey: skywin-password
      remoteRef:
        key: {{ .Values.skywin.passwordRef }}
    - secretKey: skywin-db-uri
      remoteRef:
        key: {{ .Values.skywinDb.uriRef }}
    - secretKey: common-db-uri
      remoteRef:
        key: {{ .Values.commonDb.uriRef }}
