apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pg
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/linkopingsfallskarmsklubb/infrastructure
    path: charts/postgres
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: core
  syncPolicy:
    automated:
      selfHeal: true
